services:
  - type: web
    name: allure-server
    env: docker
    dockerfilePath: ./Dockerfile.allure-server
    region: oregon
    plan: starter
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5050
    disk:
      name: allure-data
      mountPath: /app
      sizeGB: 1